version: '3.8'
services:
  mysql_db:
    image: mysql:8.0
    container_name: mysql_container_teste
    environment:
      MYSQL_ROOT_PASSWORD: senha_root
      MYSQL_DATABASE: omce_test
      MYSQL_USER: usuario_test
      MYSQL_PASSWORD: senha_test
    command: --max_allowed_packet=16M
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql  
volumes:
  mysql_data: