import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { request } from '../../api';
import AuthShell from '../../components/layout/AuthShell';
import { ErrorMessage } from '../../components/ui/Feedback';

export default function Register() {
  const navigate = useNavigate(); const [address, setAddress] = useState({}); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  const lookupCep = async (cep) => { if (cep.replace(/\D/g, '').length !== 8) return; try { const data = await fetch(`https://viacep.com.br/ws/${cep.replace(/\D/g, '')}/json/`).then((response) => response.json()); if (data.erro) throw new Error(); setAddress((current) => ({ ...current, cep, logradouro: data.logradouro, estado: data.uf, cidade: data.localidade })); } catch { setError('Não encontramos este CEP.'); } };
  const submit = async (event) => { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget)); if (values.senha !== values.confirmarSenha) return setError('As senhas não são iguais.'); setLoading(true); try { await request('/user/cadastro', { method: 'POST', body: JSON.stringify({ ...values, endereco: { ...address, pais: 'Brasil' } }) }); navigate('/login'); } catch (requestError) { setError(requestError.message); } finally { setLoading(false); } };
  return <AuthShell title="Crie sua conta" subtitle="Faça parte da comunidade O.M.C.E."><form onSubmit={submit}>{error && <ErrorMessage error={error} />}<div className="form-row"><label>Nome<input name="nome" required /></label><label>Nome de usuário<input name="nomeUser" required /></label></div><div className="form-row"><label>E-mail<input name="email" type="email" required /></label><label>Telefone<input name="telefone" required /></label></div><div className="form-row"><label>CPF<input name="cpf" inputMode="numeric" required /></label><label>Nascimento<input name="dataNasc" type="date" required /></label><label>Sexo<select name="sexo" required defaultValue=""><option value="" disabled>Selecione</option><option value="feminino">Feminino</option><option value="masculino">Masculino</option></select></label></div><label>Perfil<select name="role" required defaultValue="COMPRADOR"><option value="COMPRADOR">Comprador</option><option value="VENDEDOR">Vendedor</option><option value="MISTO">Ambos (Comprador e Vendedor)</option></select></label><label>CEP<input required value={address.cep || ''} onChange={(event) => setAddress({ ...address, cep: event.target.value })} onBlur={(event) => lookupCep(event.target.value)} /></label><div className="form-row"><label>Logradouro<input required value={address.logradouro || ''} onChange={(event) => setAddress({ ...address, logradouro: event.target.value })} /></label><label>Cidade<input required value={address.cidade || ''} onChange={(event) => setAddress({ ...address, cidade: event.target.value })} /></label><label>Estado<input required value={address.estado || ''} onChange={(event) => setAddress({ ...address, estado: event.target.value })} /></label></div><div className="form-row"><label>Senha<input name="senha" type="password" required /></label><label>Confirme a senha<input name="confirmarSenha" type="password" required /></label></div><button className="button primary full" disabled={loading}>{loading ? 'Criando conta…' : 'Criar conta'}</button></form><div className="auth-links"><p>Já possui uma conta? <Link to="/login">Entrar</Link></p></div></AuthShell>;
}
