import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { request } from '../../api';
import AuthShell from '../../components/layout/AuthShell';
import { ErrorMessage } from '../../components/ui/Feedback';
import { semNumeros, formatarTelefone, formatarCpf, formatarCep, cpfValido, telefoneValido, idadeMinimaValida, senhaForte, PATTERN_SENHA_FORTE, DICA_SENHA_FORTE, PATTERN_TELEFONE } from '../../utils/validation';

export default function Register() {
  const navigate = useNavigate(); const [address, setAddress] = useState({}); const [nome, setNome] = useState(''); const [telefone, setTelefone] = useState(''); const [cpf, setCpf] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  const lookupCep = async (cep) => { if (cep.replace(/\D/g, '').length !== 8) return; try { const data = await fetch(`https://viacep.com.br/ws/${cep.replace(/\D/g, '')}/json/`).then((response) => response.json()); if (data.erro) throw new Error(); setAddress((current) => ({ ...current, cep, logradouro: data.logradouro, estado: data.uf, cidade: data.localidade })); } catch { setError('Não encontramos este CEP.'); } };
  const submit = async (event) => { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget)); if (!telefoneValido(values.telefone)) return setError('Informe o telefone completo, com DDD.'); if (!cpfValido(values.cpf)) return setError('CPF inválido. Confira o número informado.'); if (!idadeMinimaValida(values.dataNasc)) return setError('É preciso ter pelo menos 14 anos para se cadastrar.'); if (!senhaForte(values.senha)) return setError('A senha precisa ter ao menos 8 caracteres, com letra maiúscula, minúscula, número e símbolo.'); if (values.senha !== values.confirmarSenha) return setError('As senhas não são iguais.'); setLoading(true); try { await request('/user/cadastro', { method: 'POST', body: JSON.stringify({ ...values, endereco: { ...address, pais: 'Brasil' } }) }); navigate('/login'); } catch (requestError) { setError(requestError.message); } finally { setLoading(false); } };
  return <AuthShell title="Crie sua conta" subtitle="Faça parte da comunidade O.M.C.E."><form onSubmit={submit}>{error && <ErrorMessage error={error} />}<div className="form-row"><label>Nome<input name="nome" required value={nome} onChange={(event) => setNome(semNumeros(event.target.value))} /></label><label>Nome de usuário<input name="nomeUser" required /></label></div><div className="form-row"><label>E-mail<input name="email" type="email" required /></label><label>Telefone<input name="telefone" required inputMode="numeric" value={telefone} onChange={(event) => setTelefone(formatarTelefone(event.target.value))} placeholder="(00) 00000-0000" maxLength={15} pattern={PATTERN_TELEFONE} title="Preencha o telefone completo, com DDD." /></label></div><div className="form-row"><label>CPF<input name="cpf" inputMode="numeric" required value={cpf} onChange={(event) => setCpf(formatarCpf(event.target.value))} placeholder="000.000.000-00" maxLength={14} /></label><label>Nascimento<input name="dataNasc" type="date" required min="1900-01-01" max={new Date().toISOString().slice(0, 10)} /></label><label>Sexo<select name="sexo" required defaultValue=""><option value="" disabled>Selecione</option><option value="feminino">Feminino</option><option value="masculino">Masculino</option></select></label></div><label>Perfil<select name="role" required defaultValue="COMPRADOR"><option value="COMPRADOR">Comprador</option><option value="VENDEDOR">Vendedor</option><option value="MISTO">Ambos (Comprador e Vendedor)</option></select></label><label>CEP<input required value={address.cep || ''} onChange={(event) => setAddress({ ...address, cep: formatarCep(event.target.value) })} onBlur={(event) => lookupCep(event.target.value)} placeholder="00000-000" maxLength={9} /></label><div className="form-row"><label>Logradouro<input required value={address.logradouro || ''} onChange={(event) => setAddress({ ...address, logradouro: event.target.value })} /></label><label>Cidade<input required value={address.cidade || ''} onChange={(event) => setAddress({ ...address, cidade: event.target.value })} /></label><label>Estado<input required value={address.estado || ''} onChange={(event) => setAddress({ ...address, estado: event.target.value })} /></label></div><div className="form-row"><label>Senha<input name="senha" type="password" required minLength={8} pattern={PATTERN_SENHA_FORTE} title={DICA_SENHA_FORTE} /></label><label>Confirme a senha<input name="confirmarSenha" type="password" required /></label></div><small>{DICA_SENHA_FORTE}</small><button className="button primary full" disabled={loading}>{loading ? 'Criando conta…' : 'Criar conta'}</button></form><div className="auth-links"><p>Já possui uma conta? <Link to="/login">Entrar</Link></p></div></AuthShell>;
}
