ALTER TABLE produto
    ADD COLUMN modelo VARCHAR(255) NULL,
ADD COLUMN voltagem VARCHAR(255) NULL,
ADD COLUMN carga VARCHAR(255) NULL,
ADD COLUMN comprimento VARCHAR(255) NULL,
ADD COLUMN tipo VARCHAR(255) NULL;