import { useCallback, useState } from 'react';
import { Alert, StyleSheet, View } from 'react-native';
import { useFocusEffect, useRouter } from 'expo-router';
import { Button, Empty, Loading, Message, Pagination, Screen } from '@/src/components/ui';
import { ProductCard } from '@/src/components/ProductCard';
import { api } from '@/src/lib/api';
import { PageResult, Product } from '@/src/types/models';
import { useApp } from '@/src/context/AppContext';
export default function MyProducts() { const router = useRouter(); const { session, colors, showNotice } = useApp(); const [page, setPage] = useState(0); const [result, setResult] = useState<PageResult<Product> | null>(null); const [error, setError] = useState(''); const load = useCallback(() => { if (session) api.myProducts(page, session.id).then(setResult).catch((e) => setError(e.message)); }, [page, session]); useFocusEffect(load); const remove = (product: Product) => Alert.alert('Excluir anúncio', `Excluir o anúncio “${product.nome}”?`, [{ text: 'Cancelar', style: 'cancel' }, { text: 'Excluir', style: 'destructive', onPress: async () => { try { await api.deleteProduct(product.id); showNotice('Anúncio excluído.'); load(); } catch (e) { setError(e instanceof Error ? e.message : 'Não foi possível excluir o anúncio.'); } } }]); return <Screen eyebrow="MEUS ANÚNCIOS" title="Produtos publicados" back action={<Button onPress={() => router.push('/(tabs)/anunciar')}>+ Novo</Button>}>{error ? <Message>{error}</Message> : !result ? <Loading /> : result.content.length ? <><View style={styles.list}>{result.content.map((product) => <View key={product.id} style={{ gap: 8 }}><ProductCard product={product} /><View style={styles.actions}><Button variant="secondary" onPress={() => router.push(`/produto/${product.id}/editar`)}>Editar</Button><Button variant="danger" onPress={() => remove(product)}>Excluir</Button></View></View>)}</View><Pagination page={page} totalPages={result.totalPages} first={result.first} last={result.last} onPage={setPage} /></> : <Empty title="Você ainda não publicou nada" text="Seu próximo anúncio pode ajudar alguém a criar algo novo." action={<Button onPress={() => router.push('/(tabs)/anunciar')}>Anunciar produto</Button>} />}</Screen>; }
const styles = StyleSheet.create({ list: { gap: 18 }, actions: { flexDirection: 'row', gap: 10 }, });
