import { useState } from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { useRouter } from 'expo-router';
import { Button, Empty, Field, Message, Screen } from '@/src/components/ui';
import { api, lookupCep } from '@/src/lib/api';
import { money } from '@/src/lib/format';
import { Address } from '@/src/types/models';
import { useApp } from '@/src/context/AppContext';
export default function Checkout() { const router = useRouter(); const { cart, session, clearCart, colors, showNotice } = useApp(); const [address, setAddress] = useState<Address>({ pais: 'Brasil' }); const [error, setError] = useState(''); const [saving, setSaving] = useState(false); const total = cart.reduce((sum, item) => sum + Number(item.preco), 0); const set = (key: keyof Address) => (value: string) => setAddress((current) => ({ ...current, [key]: value })); const findCep = async () => { try { const found = await lookupCep(address.cep || ''); setAddress((current) => ({ ...current, ...found })); } catch (e) { setError(e instanceof Error ? e.message : 'CEP inválido.'); } }; const submit = async () => { if (!session || !cart.length) return router.replace('/carrinho'); if (!address.cep || !address.logradouro || !address.cidade || !address.estado) return setError('Preencha o endereço de entrega.'); setSaving(true); setError(''); try { await api.checkout({ id_produtos: cart.map((item) => item.id), id_comprador: Number(session.id), endereco: { ...address, pais: 'Brasil' }, valor: total }); await clearCart(); showNotice('Pedido realizado com sucesso.'); router.replace('/historico/compras'); } catch (e) { setError(e instanceof Error ? e.message : 'Não foi possível finalizar o pedido.'); } finally { setSaving(false); } }; return <Screen eyebrow="FINALIZAR PEDIDO" title="Para onde enviamos?" back>{!cart.length ? <Empty title="Não há itens para finalizar" text="Adicione produtos ao carrinho antes de continuar." /> : <View style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.line }]}>{error && <Message>{error}</Message>}<Field label="CEP" value={address.cep || ''} onChangeText={set('cep')} onBlur={findCep} keyboardType="numeric" placeholder="00000-000" /><Field label="Logradouro" value={address.logradouro || ''} onChangeText={set('logradouro')} /><Field label="Cidade" value={address.cidade || ''} onChangeText={set('cidade')} /><Field label="Estado" value={address.estado || ''} onChangeText={set('estado')} autoCapitalize="characters" /><View style={[styles.total, { borderTopColor: colors.line }]}><Text style={{ color: colors.ink }}>Total do pedido</Text><Text style={{ color: colors.green, fontFamily: 'Manrope_800ExtraBold', fontSize: 18 }}>{money(total)}</Text></View><Button onPress={submit} disabled={saving}>{saving ? 'Finalizando…' : 'Confirmar pedido'}</Button></View>}</Screen>; }
const styles = StyleSheet.create({ card: { borderWidth: 1, borderRadius: 9, padding: 18, gap: 16 }, total: { borderTopWidth: 1, paddingTop: 16, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', fontFamily: 'Manrope_700Bold' } });
