import React, { createContext, useContext, useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter, Link, NavLink, Navigate, Route, Routes, useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { auth, cartKey, getCart, imageSource, money, request, saveCart } from './api';
import './styles.css';

const NoticeContext = createContext(() => {});
const useNotice = () => useContext(NoticeContext);
const ThemeContext = createContext({ theme: 'light', toggleTheme: () => {} });
const useTheme = () => useContext(ThemeContext);

function App() {
  const [notice, setNotice] = useState(null);
  const [theme, setTheme] = useState(() => localStorage.getItem('theme') || (window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light'));
  useEffect(() => { document.documentElement.dataset.theme = theme; document.documentElement.style.colorScheme = theme; localStorage.setItem('theme', theme); }, [theme]);
  const toggleTheme = () => setTheme((current) => current === 'dark' ? 'light' : 'dark');
  return <ThemeContext.Provider value={{ theme, toggleTheme }}><NoticeContext.Provider value={setNotice}>
    <BrowserRouter><Routes>
      <Route path="/login" element={<Guest><Login /></Guest>} />
      <Route path="/cadastro" element={<Guest><Register /></Guest>} />
      <Route path="/redefinir-senha" element={<Guest><PasswordReset /></Guest>} />
      <Route path="/nova-senha" element={<Guest><NewPassword /></Guest>} />
      <Route path="/*" element={<Protected><Layout><AppRoutes /></Layout></Protected>} />
    </Routes></BrowserRouter>
    {notice && <div className={`toast ${notice.type || 'success'}`} role="status">{notice.message}<button onClick={() => setNotice(null)}>×</button></div>}
  </NoticeContext.Provider></ThemeContext.Provider>;
}

function Guest({ children }) { return auth.loggedIn() ? <Navigate to="/" replace /> : children; }
function Protected({ children }) { return auth.loggedIn() ? children : <Navigate to="/login" replace />; }

function Layout({ children }) {
  const navigate = useNavigate();
  const { theme, toggleTheme } = useTheme();
  const [cartSize, setCartSize] = useState(getCart().length);
  useEffect(() => { const update = () => setCartSize(getCart().length); window.addEventListener('storage', update); window.addEventListener('cart-updated', update); return () => { window.removeEventListener('storage', update); window.removeEventListener('cart-updated', update); }; }, []);
  const logout = () => { auth.clear(); navigate('/login'); };
  const nav = [['/', 'Início'], ['/feed', 'Explorar'], ['/produto/novo', 'Anunciar'], ['/minha-conta', 'Minha conta']];
  return <><header className="topbar"><Link className="brand" to="/"><span className="brand-mark">◈</span><span>O.M.C.E</span></Link><nav>{nav.map(([to, label]) => <NavLink key={to} to={to} end={to === '/'}>{label}</NavLink>)}</nav><div className="top-actions"><ThemeToggle theme={theme} onToggle={toggleTheme} /><Link className="cart-button" to="/carrinho" aria-label="Carrinho">🛒<b>{cartSize}</b></Link><details className="account-menu"><summary>{auth.name || 'Minha conta'}</summary><div><Link to="/meus-produtos">Meus produtos</Link><Link to="/historico/compras">Minhas compras</Link><Link to="/historico/vendas">Minhas vendas</Link><Link to="/avaliacoes">Minhas avaliações</Link><button onClick={logout}>Sair</button></div></details></div></header><main>{children}</main></>;
}

function ThemeToggle({ theme, onToggle, className = '' }) { const isDark = theme === 'dark'; return <button type="button" className={`theme-toggle ${className}`} onClick={onToggle} aria-label={`Ativar tema ${isDark ? 'claro' : 'escuro'}`} aria-pressed={isDark} title={`Ativar tema ${isDark ? 'claro' : 'escuro'}`}><span aria-hidden="true">{isDark ? '☀' : '☾'}</span><span className="theme-toggle-label">{isDark ? 'Claro' : 'Escuro'}</span></button>; }

function AppRoutes() { return <Routes>
  <Route index element={<Home />} /><Route path="feed" element={<Feed />} /><Route path="produto/novo" element={<ProductForm />} /><Route path="produto/:id/editar" element={<ProductForm edit />} /><Route path="produto/:id" element={<ProductDetail />} />
  <Route path="carrinho" element={<Cart />} /><Route path="pedido" element={<Checkout />} /><Route path="minha-conta" element={<Profile />} /><Route path="meus-produtos" element={<MyProducts />} />
  <Route path="historico/:type" element={<History />} /><Route path="avaliacoes" element={<SellerReviews />} /><Route path="produto/:id/avaliacoes" element={<ProductReviews />} /><Route path="vendedor/:id/avaliar" element={<SellerReviewForm />} />
  <Route path="*" element={<Navigate to="/" replace />} />
</Routes>; }

function Page({ eyebrow, title, children, actions }) { return <section className="page"><div className="page-heading"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1></div>{actions}</div>{children}</section>; }
function Empty({ title, text, action }) { return <div className="empty"><span>⌁</span><h2>{title}</h2><p>{text}</p>{action}</div>; }
function Loading() { return <div className="loading">Carregando…</div>; }
function ErrorMessage({ error }) { return <div className="feedback error">{error}</div>; }

function Home() {
  const [products, setProducts] = useState([]); const [error, setError] = useState('');
  useEffect(() => { request('/produto/filtro?page=0').then((data) => setProducts((data.content || []).slice(-3))).catch((e) => setError(e.message)); }, []);
  return <><section className="hero"><div><p className="eyebrow">COMPRA E VENDA DE ELETRÔNICOS</p><h1>Peças que movem <em>ideias.</em></h1><p className="hero-copy">Encontre componentes eletrônicos, dê novo destino ao que já não usa e transforme projetos em realidade.</p><div className="hero-actions"><Link className="button primary" to="/feed">Explorar produtos</Link><Link className="button secondary" to="/produto/novo">Anunciar peça</Link></div></div><div className="hero-art"><span>⚡</span><p>Do circuito<br />à criação.</p></div></section><Page eyebrow="RECÉM-CHEGADOS" title="Novidades no mercado" actions={<Link className="text-link" to="/feed">Ver todos →</Link>}>{error ? <ErrorMessage error={error} /> : products.length ? <ProductGrid products={products} /> : <Loading />}</Page></>;
}

function ProductGrid({ products, onDelete }) { return <div className="product-grid">{products.map((product) => <ProductCard key={product.id} product={product} onDelete={onDelete} />)}</div>; }
function ProductCard({ product, onDelete }) { const image = imageSource(product); return <article className="product-card"><Link to={`/produto/${product.id}`} className="product-image">{image ? <img src={image} alt={product.nome} /> : <span>Sem imagem</span>}<small>{product.condicao || 'Disponível'}</small></Link><div className="product-info"><p className="category">{product.categoria || 'ELETRÔNICOS'}</p><Link to={`/produto/${product.id}`}><h2>{product.nome}</h2></Link><p className="seller">por {product.nomeUsuario || product.nome_do_usuario || 'Vendedor O.M.C.E'}</p><div className="product-footer"><strong>{money(product.preco)}</strong>{onDelete && <div className="card-actions"><Link to={`/produto/${product.id}/editar`}>Editar</Link><button className="danger-text" onClick={() => onDelete(product)}>Excluir</button></div>}</div></div></article>; }

function Feed() {
  const [products, setProducts] = useState([]); const [filters, setFilters] = useState({ nome: '', categoria: '', precoMin: '', precoMax: '' }); const [page, setPage] = useState(0); const [result, setResult] = useState(null); const [error, setError] = useState('');
  useEffect(() => { const q = new URLSearchParams({ page }); Object.entries(filters).forEach(([k, v]) => v && q.set(k, v)); setResult(null); request(`/produto/filtro?${q}`).then((data) => { setProducts(data.content || []); setResult(data); }).catch((e) => setError(e.message)); }, [page, filters]);
  const update = (event) => { event.preventDefault(); setPage(0); setFilters(Object.fromEntries(new FormData(event.currentTarget))); };
  return <Page eyebrow="MERCADO O.M.C.E" title="Explore componentes" actions={<Link className="button primary" to="/produto/novo">+ Anunciar produto</Link>}><form className="filters" onSubmit={update}><input name="nome" placeholder="Busque por nome" defaultValue={filters.nome} /><select name="categoria" defaultValue={filters.categoria}><option value="">Todas as categorias</option>{['ESP32', 'ARDUINO', 'REGISTORES', 'SENSORES', 'BATERIA', 'CABOS', 'MOTORES', 'CONECTORES', 'OUTRO'].map((item) => <option key={item}>{item}</option>)}</select><input name="precoMin" type="number" min="0" placeholder="Preço mínimo" defaultValue={filters.precoMin} /><input name="precoMax" type="number" min="0" placeholder="Preço máximo" defaultValue={filters.precoMax} /><button className="button primary">Filtrar</button></form>{error ? <ErrorMessage error={error} /> : result === null ? <Loading /> : products.length ? <><ProductGrid products={products} /><Pagination page={page} result={result} onPage={setPage} /></> : <Empty title="Nenhum produto encontrado" text="Tente ajustar seus filtros para descobrir mais peças." />}</Page>;
}

function Pagination({ page, result, onPage }) { if (!result || result.totalPages <= 1) return null; return <div className="pagination"><button disabled={result.first} onClick={() => onPage(page - 1)}>← Anterior</button><span>Página {page + 1} de {result.totalPages}</span><button disabled={result.last} onClick={() => onPage(page + 1)}>Próxima →</button></div>; }

function ProductDetail() {
  const { id } = useParams(); const [product, setProduct] = useState(null); const [rating, setRating] = useState(null); const [error, setError] = useState(''); const notice = useNotice();
  useEffect(() => { request(`/produto/visualizarDetalhesProduto/${id}`).then(setProduct).catch((e) => setError(e.message)); }, [id]);
  useEffect(() => { if (product?.id_vendedor) request(`/avaliacaoVendedor/media/${product.id_vendedor}`).then(setRating).catch(() => {}); }, [product]);
  const addToCart = () => { const cart = getCart(); if (!cart.some((item) => item.id === product.id)) saveCart([...cart, { id: product.id, nome: product.nome, preco: product.preco, imagem: product.imagem ?? product.Imagem, imagem_tipo: product.imagem_tipo ?? product.Imagem_tipo }]); window.dispatchEvent(new Event('cart-updated')); notice({ message: 'Produto adicionado ao carrinho.' }); };
  if (error) return <Page eyebrow="PRODUTO" title="Não foi possível abrir o produto"><ErrorMessage error={error} /></Page>; if (!product) return <Loading />; const image = imageSource(product);
  return <section className="detail-page"><Link className="back-link" to="/feed">← Voltar ao catálogo</Link><div className="product-detail"><div className="detail-image">{image ? <img src={image} alt={product.nome} /> : 'Sem imagem'}</div><div className="detail-content"><p className="eyebrow">{product.categoria || 'ELETRÔNICOS'} · {product.condicao}</p><h1>{product.nome}</h1><strong className="detail-price">{money(product.preco)}</strong><p className="detail-description">{product.detalhes || 'Este vendedor ainda não adicionou detalhes a este anúncio.'}</p><div className="seller-box"><span>Vendido por</span><b>{product.nome_do_usuario || product.nomeUsuario || 'Vendedor O.M.C.E'}</b>{rating !== null && <small>★ {Number(rating).toFixed(1)} de avaliação</small>}</div><div className="detail-actions"><button className="button primary" onClick={addToCart}>Adicionar ao carrinho</button><Link className="button secondary" to={`/produto/${id}/avaliacoes`}>Ver avaliações</Link></div></div></div></section>;
}

function ProductForm({ edit = false }) {
  const { id } = useParams(); const navigate = useNavigate(); const notice = useNotice(); const [current, setCurrent] = useState(null); const [file, setFile] = useState(null); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  useEffect(() => { if (edit) request(`/produto/visualizarDetalhesProduto/${id}`).then(setCurrent).catch((e) => setError(e.message)); }, [edit, id]);
  const submit = async (event) => { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget)); if (!edit && !file) return setError('Escolha uma imagem para anunciar o produto.'); setSaving(true); setError(''); try { const base64 = file ? await fileToData(file) : null; const product = { id: current?.id, nome: values.nome, preco: Number(values.preco), detalhes: values.detalhes, condicao: values.condicao, categoria: values.categoria, id_usuario: Number(auth.userId), imagem: base64?.data || current?.imagem || current?.Imagem, imagem_tipo: base64?.type || current?.imagem_tipo || current?.Imagem_tipo }; await request(edit ? '/produto/alterarDadosProduto' : '/produto/cadastroProduto', { method: edit ? 'PUT' : 'POST', body: JSON.stringify(product) }); notice({ message: edit ? 'Produto atualizado com sucesso.' : 'Produto anunciado com sucesso.' }); navigate(edit ? `/produto/${id}` : '/feed'); } catch (e) { setError(e.message); } finally { setSaving(false); } };
  if (edit && !current && !error) return <Loading />; return <Page eyebrow={edit ? 'GERENCIAR ANÚNCIO' : 'NOVO ANÚNCIO'} title={edit ? 'Edite seu produto' : 'Anuncie uma peça'}><form className="form-card product-form" onSubmit={submit}>{error && <ErrorMessage error={error} />}<label>Nome do produto<input name="nome" required defaultValue={current?.nome} placeholder="Ex.: Kit ESP32 DevKit" /></label><div className="form-row"><label>Preço<input name="preco" type="number" min="0.01" step="0.01" required defaultValue={current?.preco} placeholder="0,00" /></label><label>Condição<select name="condicao" required defaultValue={current?.condicao || ''}><option value="" disabled>Selecione</option><option value="NOVO">Novo</option><option value="USADO">Usado</option></select></label><label>Categoria<select name="categoria" required defaultValue={current?.categoria || ''}><option value="" disabled>Selecione</option>{['ESP32', 'ARDUINO', 'REGISTORES', 'SENSORES', 'BATERIA', 'CABOS', 'MOTORES', 'CONECTORES', 'OUTRO'].map((item) => <option key={item}>{item}</option>)}</select></label></div><label>Detalhes<textarea name="detalhes" required defaultValue={current?.detalhes} placeholder="Descreva o estado, especificações e o que acompanha o produto." rows="5" /></label><label>Imagem<input type="file" accept="image/*" onChange={(event) => setFile(event.target.files?.[0])} />{current && !file && <small>Deixe em branco para manter a imagem atual.</small>}</label><button className="button primary" disabled={saving}>{saving ? 'Salvando…' : edit ? 'Salvar alterações' : 'Publicar anúncio'}</button></form></Page>;
}

function Cart() { const navigate = useNavigate(); const [items, setItems] = useState(getCart()); const total = items.reduce((sum, item) => sum + Number(item.preco), 0); const remove = (id) => { const updated = items.filter((item) => item.id !== id); setItems(updated); saveCart(updated); window.dispatchEvent(new Event('cart-updated')); }; return <Page eyebrow="SEU CARRINHO" title="Pronto para levar?">{items.length ? <div className="cart-layout"><div className="cart-list">{items.map((item) => <div className="cart-item" key={item.id}>{imageSource(item) && <img src={imageSource(item)} alt="" />}<div><h2>{item.nome}</h2><p>{money(item.preco)}</p></div><button className="danger-text" onClick={() => remove(item.id)}>Remover</button></div>)}</div><aside className="order-summary"><p>Resumo do pedido</p><div><span>{items.length} item(ns)</span><span>{money(total)}</span></div><hr /><strong>Total <span>{money(total)}</span></strong><button className="button primary" onClick={() => navigate('/pedido')}>Continuar para entrega</button></aside></div> : <Empty title="Seu carrinho está vazio" text="Explore o catálogo e encontre peças para o seu próximo projeto." action={<Link className="button primary" to="/feed">Explorar produtos</Link>} />}</Page>; }

function Checkout() { const navigate = useNavigate(); const notice = useNotice(); const [address, setAddress] = useState({}); const [error, setError] = useState(''); const [saving, setSaving] = useState(false); const items = getCart(); const total = items.reduce((sum, item) => sum + Number(item.preco), 0); const lookupCep = async (cep) => { if (cep.replace(/\D/g, '').length !== 8) return; try { const data = await fetch(`https://viacep.com.br/ws/${cep.replace(/\D/g, '')}/json/`).then((r) => r.json()); if (data.erro) throw new Error(); setAddress((old) => ({ ...old, cep, logradouro: data.logradouro, estado: data.uf, cidade: data.localidade })); } catch { setError('CEP não encontrado. Confira o número informado.'); } };
  const submit = async (event) => { event.preventDefault(); if (!items.length) return navigate('/carrinho'); setSaving(true); setError(''); try { await request('/pedido/cadastro', { method: 'POST', body: JSON.stringify({ id_produtos: items.map((item) => item.id), id_comprador: Number(auth.userId), endereco: { ...address, pais: 'Brasil' }, valor: total }) }); localStorage.removeItem(cartKey()); window.dispatchEvent(new Event('cart-updated')); notice({ message: 'Pedido realizado com sucesso.' }); navigate('/historico/compras'); } catch (e) { setError(e.message); } finally { setSaving(false); } };
  return <Page eyebrow="FINALIZAR PEDIDO" title="Para onde enviamos?">{!items.length ? <Empty title="Não há itens para finalizar" text="Adicione produtos ao carrinho antes de continuar." /> : <form className="form-card checkout-form" onSubmit={submit}>{error && <ErrorMessage error={error} />}<label>CEP<input required value={address.cep || ''} onChange={(e) => setAddress({ ...address, cep: e.target.value })} onBlur={(e) => lookupCep(e.target.value)} placeholder="00000-000" /></label><label>Logradouro<input required value={address.logradouro || ''} onChange={(e) => setAddress({ ...address, logradouro: e.target.value })} /></label><div className="form-row"><label>Estado<input required value={address.estado || ''} onChange={(e) => setAddress({ ...address, estado: e.target.value })} /></label><label>Cidade<input required value={address.cidade || ''} onChange={(e) => setAddress({ ...address, cidade: e.target.value })} /></label></div><div className="checkout-total">Total do pedido <strong>{money(total)}</strong></div><button className="button primary" disabled={saving}>{saving ? 'Finalizando…' : 'Confirmar pedido'}</button></form>}</Page>;
}

function Profile() { const notice = useNotice(); const [user, setUser] = useState(null); const [address, setAddress] = useState({}); const [error, setError] = useState(''); const [saving, setSaving] = useState(false); useEffect(() => { request(`/user/${auth.userId}`).then((data) => { setUser(data); setAddress(data.endereco || {}); }).catch((e) => setError(e.message)); }, []); const submit = async (event) => { event.preventDefault(); const v = Object.fromEntries(new FormData(event.currentTarget)); setSaving(true); try { await request('/user/alterardados', { method: 'PUT', body: JSON.stringify({ ...user, ...v, id: Number(auth.userId), endereco: { ...address, pais: 'Brasil' }, novaSenha: v.novaSenha }) }); localStorage.setItem('nome', v.nome); notice({ message: 'Dados atualizados com sucesso.' }); } catch (e) { setError(e.message); } finally { setSaving(false); } }; if (!user && !error) return <Loading />; return <Page eyebrow="MINHA CONTA" title="Seus dados">{error ? <ErrorMessage error={error} /> : <form className="form-card profile-form" onSubmit={submit}><div className="form-row"><label>Nome<input name="nome" defaultValue={user.nome} required /></label><label>Nome de usuário<input name="nomeUser" defaultValue={user.nomeUser} required /></label></div><div className="form-row"><label>E-mail<input name="email" type="email" defaultValue={user.email} required /></label><label>Telefone<input name="telefone" defaultValue={user.telefone} required /></label></div><div className="form-row"><label>CPF<input name="cpf" defaultValue={user.cpf} required /></label><label>Data de nascimento<input name="dataNasc" type="date" defaultValue={user.dataNasc} required /></label></div><h2>Endereço</h2><label>CEP<input value={address.cep || ''} onChange={(e) => setAddress({ ...address, cep: e.target.value })} /></label><div className="form-row"><label>Logradouro<input value={address.logradouro || ''} onChange={(e) => setAddress({ ...address, logradouro: e.target.value })} /></label><label>Cidade<input value={address.cidade || ''} onChange={(e) => setAddress({ ...address, cidade: e.target.value })} /></label><label>Estado<input value={address.estado || ''} onChange={(e) => setAddress({ ...address, estado: e.target.value })} /></label></div><h2>Segurança</h2><div className="form-row"><label>Senha atual<input type="password" name="senha" required /></label><label>Nova senha <small>(opcional)</small><input type="password" name="novaSenha" /></label></div><button className="button primary" disabled={saving}>{saving ? 'Salvando…' : 'Salvar alterações'}</button></form>}</Page>; }

function MyProducts() { const [result, setResult] = useState(null); const [page, setPage] = useState(0); const [error, setError] = useState(''); const notice = useNotice(); const load = () => request(`/produto/todosProdutosUsuario?page=${page}`, { headers: { 'Id-Usuario': auth.userId } }).then(setResult).catch((e) => setError(e.message)); useEffect(load, [page]); const remove = async (product) => { if (!window.confirm(`Excluir o anúncio “${product.nome}”?`)) return; try { await request(`/produto/deletar/${product.id}`, { method: 'DELETE' }); notice({ message: 'Anúncio excluído.' }); load(); } catch (e) { setError(e.message); } }; return <Page eyebrow="MEUS ANÚNCIOS" title="Produtos publicados" actions={<Link className="button primary" to="/produto/novo">+ Novo anúncio</Link>}>{error ? <ErrorMessage error={error} /> : !result ? <Loading /> : result.content?.length ? <><ProductGrid products={result.content} onDelete={remove} /><Pagination page={page} result={result} onPage={setPage} /></> : <Empty title="Você ainda não publicou nada" text="Seu próximo anúncio pode ajudar alguém a criar algo novo." action={<Link className="button primary" to="/produto/novo">Anunciar produto</Link>} />}</Page>; }

function History() { const { type } = useParams(); const [result, setResult] = useState(null); const [page, setPage] = useState(0); const [error, setError] = useState(''); const purchases = type === 'compras'; useEffect(() => { setResult(null); request(`/historico/${purchases ? 'compra' : 'vendas'}?page=${page}`, { headers: { 'Id-Usuario': auth.userId } }).then(setResult).catch((e) => setError(e.message)); }, [page, purchases]); return <Page eyebrow="HISTÓRICO" title={purchases ? 'Minhas compras' : 'Minhas vendas'}>{error ? <ErrorMessage error={error} /> : !result ? <Loading /> : result.content?.length ? <><div className="history-list">{result.content.map((product) => <HistoryItem key={product.id} product={product} purchases={purchases} />)}</div><Pagination page={page} result={result} onPage={setPage} /></> : <Empty title="Ainda não há movimentações" text={purchases ? 'As suas compras aparecerão aqui.' : 'As vendas dos seus produtos aparecerão aqui.'} />}</Page>; }
function HistoryItem({ product, purchases }) { const image = imageSource(product); return <article className="history-item">{image && <img src={image} alt="" />}<div><p className="category">{product.categoria || 'PRODUTO'}</p><h2>{product.nome}</h2><strong>{money(product.preco)}</strong></div><div className="history-actions"><Link to={`/produto/${product.id}`}>Ver produto</Link>{purchases && <><Link to={`/produto/${product.id}/avaliacoes`}>Avaliar produto</Link>{product.id_vendedor && <Link to={`/vendedor/${product.id_vendedor}/avaliar`}>Avaliar vendedor</Link>}</>}</div></article>; }

function ProductReviews() { const { id } = useParams(); const [result, setResult] = useState(null); const [page, setPage] = useState(0); const [error, setError] = useState(''); useEffect(() => { setResult(null); request(`/avaliacoes/produto/${id}?page=${page}`).then(setResult).catch((e) => setError(e.message)); }, [id, page]); return <ReviewsPage eyebrow="AVALIAÇÕES" title="O que dizem sobre o produto" result={result} error={error} page={page} setPage={setPage} />; }
function SellerReviews() { const [result, setResult] = useState(null); const [page, setPage] = useState(0); const [error, setError] = useState(''); useEffect(() => { setResult(null); request(`/avaliacaoVendedor/${auth.userId}?page=${page}`).then(setResult).catch((e) => setError(e.message)); }, [page]); return <ReviewsPage eyebrow="MINHAS AVALIAÇÕES" title="Sua reputação" result={result} error={error} page={page} setPage={setPage} />; }
function ReviewsPage({ eyebrow, title, result, error, page, setPage }) { return <Page eyebrow={eyebrow} title={title}>{error ? <ErrorMessage error={error} /> : !result ? <Loading /> : result.content?.length ? <><div className="reviews">{result.content.map((review, i) => <article className="review" key={review.id || i}><strong>★ {review.nota}/5</strong><p>{review.comentario || 'Sem comentário.'}</p></article>)}</div><Pagination page={page} result={result} onPage={setPage} /></> : <Empty title="Ainda não há avaliações" text="Quando alguém avaliar, os comentários aparecerão aqui." />}</Page>; }

function SellerReviewForm() { const { id } = useParams(); const navigate = useNavigate(); const notice = useNotice(); const [error, setError] = useState(''); const [saving, setSaving] = useState(false); const submit = async (event) => { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget)); setSaving(true); try { await request('/avaliacaoVendedor/cadastro', { method: 'POST', body: JSON.stringify({ nota: Number(values.nota), comentario: values.comentario, vendedor_id: Number(id) }) }); notice({ message: 'Avaliação enviada. Obrigado!' }); navigate('/historico/compras'); } catch (e) { setError(e.message); } finally { setSaving(false); } }; return <Page eyebrow="AVALIAR VENDEDOR" title="Como foi sua experiência?"><form className="form-card compact-form" onSubmit={submit}>{error && <ErrorMessage error={error} />}<label>Nota<select name="nota" required defaultValue=""><option value="" disabled>Selecione de 1 a 5</option>{[1, 2, 3, 4, 5].map((n) => <option key={n} value={n}>{n} estrela{n > 1 ? 's' : ''}</option>)}</select></label><label>Comentário<textarea name="comentario" required rows="5" placeholder="Conte como foi a compra." /></label><button className="button primary" disabled={saving}>{saving ? 'Enviando…' : 'Enviar avaliação'}</button></form></Page>; }

function Login() { const navigate = useNavigate(); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); const submit = async (event) => { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget)); setLoading(true); setError(''); try { const data = await request('/auth/login', { method: 'POST', body: JSON.stringify(values) }); auth.save(data); navigate('/'); } catch (e) { setError(e.message || 'E-mail ou senha inválidos.'); } finally { setLoading(false); } }; return <AuthShell title="Acesse sua conta" subtitle="Entre para comprar, vender e criar."><form onSubmit={submit}>{error && <ErrorMessage error={error} />}<label>E-mail<input name="email" type="email" required autoComplete="email" /></label><label>Senha<input name="senha" type="password" required autoComplete="current-password" /></label><button className="button primary full" disabled={loading}>{loading ? 'Entrando…' : 'Entrar'}</button></form><div className="auth-links"><Link to="/redefinir-senha">Esqueci minha senha</Link><p>Ainda não tem conta? <Link to="/cadastro">Cadastre-se</Link></p></div></AuthShell>; }
function Register() { const navigate = useNavigate(); const [address, setAddress] = useState({}); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); const lookupCep = async (cep) => { if (cep.replace(/\D/g, '').length !== 8) return; try { const data = await fetch(`https://viacep.com.br/ws/${cep.replace(/\D/g, '')}/json/`).then((r) => r.json()); if (data.erro) throw new Error(); setAddress((a) => ({ ...a, cep, logradouro: data.logradouro, estado: data.uf, cidade: data.localidade })); } catch { setError('Não encontramos este CEP.'); } }; const submit = async (event) => { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget)); if (values.senha !== values.confirmarSenha) return setError('As senhas não são iguais.'); setLoading(true); try { await request('/user/cadastro', { method: 'POST', body: JSON.stringify({ ...values, endereco: { ...address, pais: 'Brasil' } }) }); navigate('/login'); } catch (e) { setError(e.message); } finally { setLoading(false); } }; return <AuthShell title="Crie sua conta" subtitle="Faça parte da comunidade O.M.C.E."><form onSubmit={submit}>{error && <ErrorMessage error={error} />}<div className="form-row"><label>Nome<input name="nome" required /></label><label>Nome de usuário<input name="nomeUser" required /></label></div><div className="form-row"><label>E-mail<input name="email" type="email" required /></label><label>Telefone<input name="telefone" required /></label></div><div className="form-row"><label>CPF<input name="cpf" inputMode="numeric" required /></label><label>Nascimento<input name="dataNasc" type="date" required /></label><label>Sexo<select name="sexo" required defaultValue=""><option value="" disabled>Selecione</option><option value="feminino">Feminino</option><option value="masculino">Masculino</option></select></label></div><label>CEP<input required value={address.cep || ''} onChange={(e) => setAddress({ ...address, cep: e.target.value })} onBlur={(e) => lookupCep(e.target.value)} /></label><div className="form-row"><label>Logradouro<input required value={address.logradouro || ''} onChange={(e) => setAddress({ ...address, logradouro: e.target.value })} /></label><label>Cidade<input required value={address.cidade || ''} onChange={(e) => setAddress({ ...address, cidade: e.target.value })} /></label><label>Estado<input required value={address.estado || ''} onChange={(e) => setAddress({ ...address, estado: e.target.value })} /></label></div><div className="form-row"><label>Senha<input name="senha" type="password" required /></label><label>Confirme a senha<input name="confirmarSenha" type="password" required /></label></div><button className="button primary full" disabled={loading}>{loading ? 'Criando conta…' : 'Criar conta'}</button></form><div className="auth-links"><p>Já possui uma conta? <Link to="/login">Entrar</Link></p></div></AuthShell>; }
function PasswordReset() { const [message, setMessage] = useState(''); const [error, setError] = useState(''); const submit = async (event) => { event.preventDefault(); try { await request('/user/redefinirSenha', { method: 'POST', body: JSON.stringify(Object.fromEntries(new FormData(event.currentTarget))) }); setMessage('Enviamos as instruções para seu e-mail.'); } catch (e) { setError(e.message); } }; return <AuthShell title="Redefinir senha" subtitle="Informe seu e-mail para receber as instruções."><form onSubmit={submit}>{error && <ErrorMessage error={error} />}{message && <div className="feedback success">{message}</div>}<label>E-mail<input name="email" type="email" required /></label><button className="button primary full">Enviar instruções</button></form><div className="auth-links"><Link to="/login">Voltar para entrar</Link></div></AuthShell>; }
function NewPassword() { const navigate = useNavigate(); const [error, setError] = useState(''); const [params] = useSearchParams(); const submit = async (event) => { event.preventDefault(); const v = Object.fromEntries(new FormData(event.currentTarget)); if (v.senha !== v.confirmarSenha) return setError('As senhas não coincidem.'); try { await request('/user/novaSenha', { method: 'PUT', body: JSON.stringify({ token: params.get('token'), senha: v.senha }) }); navigate('/login'); } catch (e) { setError(e.message); } }; return <AuthShell title="Escolha uma nova senha" subtitle="Use uma senha forte e que você não use em outros sites."><form onSubmit={submit}>{error && <ErrorMessage error={error} />}<label>Nova senha<input name="senha" type="password" required /></label><label>Confirme a nova senha<input name="confirmarSenha" type="password" required /></label><button className="button primary full">Atualizar senha</button></form></AuthShell>; }
function AuthShell({ title, subtitle, children }) { const { theme, toggleTheme } = useTheme(); return <div className="auth-page"><Link className="brand auth-brand" to="/login"><span className="brand-mark">◈</span> O.M.C.E</Link><ThemeToggle theme={theme} onToggle={toggleTheme} className="auth-theme-toggle" /><section className="auth-card"><p className="eyebrow">MERCADO DE ELETRÔNICOS</p><h1>{title}</h1><p className="auth-subtitle">{subtitle}</p>{children}</section><p className="auth-aside">Componentes, projetos e possibilidades.<br /><strong>Todo circuito começa com uma peça.</strong></p></div>; }

function fileToData(file) { return new Promise((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve({ data: reader.result.split(',')[1], type: file.type }); reader.onerror = reject; reader.readAsDataURL(file); }); }
createRoot(document.getElementById('root')).render(<React.StrictMode><App /></React.StrictMode>);
