import { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { auth, request } from '../../api';
import { useNotice } from '../../contexts/NoticeContext';
import { ErrorMessage, Loading } from '../../components/ui/Feedback';
import Page from '../../components/ui/Page';
import fileToData from '../../utils/fileToData';

export default function ProductForm({ edit = false }) {
  const { id } = useParams(); const navigate = useNavigate(); const notice = useNotice(); const [current, setCurrent] = useState(null); const [file, setFile] = useState(null); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  useEffect(() => { if (edit) request(`/produto/visualizarDetalhesProduto/${id}`).then(setCurrent).catch((requestError) => setError(requestError.message)); }, [edit, id]);
  const submit = async (event) => { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget)); if (!edit && !file) return setError('Escolha uma imagem para anunciar o produto.'); setSaving(true); setError(''); try { const base64 = file ? await fileToData(file) : null; const product = { id: current?.id, nome: values.nome, preco: Number(values.preco), detalhes: values.detalhes, condicao: values.condicao, categoria: values.categoria, id_usuario: Number(auth.userId), imagem: base64?.data || current?.imagem || current?.Imagem, imagem_tipo: base64?.type || current?.imagem_tipo || current?.Imagem_tipo }; await request(edit ? '/produto/alterarDadosProduto' : '/produto/cadastroProduto', { method: edit ? 'PUT' : 'POST', body: JSON.stringify(product) }); notice({ message: edit ? 'Produto atualizado com sucesso.' : 'Produto anunciado com sucesso.' }); navigate(edit ? `/produto/${id}` : '/feed'); } catch (requestError) { setError(requestError.message); } finally { setSaving(false); } };
  if (edit && !current && !error) return <Loading />;
  return <Page eyebrow={edit ? 'GERENCIAR ANÚNCIO' : 'NOVO ANÚNCIO'} title={edit ? 'Edite seu produto' : 'Anuncie uma peça'}><form className="form-card product-form" onSubmit={submit}>{error && <ErrorMessage error={error} />}<label>Nome do produto<input name="nome" required defaultValue={current?.nome} placeholder="Ex.: Kit ESP32 DevKit" /></label><div className="form-row"><label>Preço<input name="preco" type="number" min="0.01" step="0.01" required defaultValue={current?.preco} placeholder="0,00" /></label><label>Condição<select name="condicao" required defaultValue={current?.condicao || ''}><option value="" disabled>Selecione</option><option value="NOVO">Novo</option><option value="USADO">Usado</option></select></label><label>Categoria<select name="categoria" required defaultValue={current?.categoria || ''}><option value="" disabled>Selecione</option>{['ESP32', 'ARDUINO', 'REGISTORES', 'SENSORES', 'BATERIA', 'CABOS', 'MOTORES', 'CONECTORES', 'OUTRO'].map((item) => <option key={item}>{item}</option>)}</select></label></div><label>Detalhes<textarea name="detalhes" required defaultValue={current?.detalhes} placeholder="Descreva o estado, especificações e o que acompanha o produto." rows="5" /></label><label>Imagem<input type="file" accept="image/*" onChange={(event) => setFile(event.target.files?.[0])} />{current && !file && <small>Deixe em branco para manter a imagem atual.</small>}</label><button className="button primary" disabled={saving}>{saving ? 'Salvando…' : edit ? 'Salvar alterações' : 'Publicar anúncio'}</button></form></Page>;
}
