import { useEffect, useState } from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { Button, Choice, Empty, Field, Loading, Message, Pagination, Screen } from '@/src/components/ui';
import { ProductCard } from '@/src/components/ProductCard';
import { categoryOptions } from '@/src/constants/theme';
import { api } from '@/src/lib/api';
import { queryString } from '@/src/lib/format';
import { PageResult, Product } from '@/src/types/models';
import { useApp } from '@/src/context/AppContext';
export default function Feed() { const { colors } = useApp(); const [name, setName] = useState(''); const [category, setCategory] = useState(''); const [min, setMin] = useState(''); const [max, setMax] = useState(''); const [submitted, setSubmitted] = useState({ nome: '', categoria: '', precoMin: '', precoMax: '' }); const [page, setPage] = useState(0); const [result, setResult] = useState<PageResult<Product> | null>(null); const [error, setError] = useState(''); useEffect(() => { setResult(null); api.products(queryString({ page, ...submitted })).then(setResult).catch((e) => setError(e.message)); }, [page, submitted]); const filter = () => { setPage(0); setSubmitted({ nome: name, categoria: category, precoMin: min, precoMax: max }); }; return <Screen eyebrow="MERCADO O.M.C.E" title="Explore componentes"><View style={[styles.filters, { backgroundColor: colors.surface, borderColor: colors.line }]}><Field label="Busque por nome" value={name} onChangeText={setName} /><Choice label="Categoria" value={category} options={['', ...categoryOptions]} onChange={setCategory} /><View style={styles.row}><View style={{ flex: 1 }}><Field label="Preço mínimo" value={min} onChangeText={setMin} keyboardType="decimal-pad" /></View><View style={{ flex: 1 }}><Field label="Preço máximo" value={max} onChangeText={setMax} keyboardType="decimal-pad" /></View></View><Button onPress={filter}>Filtrar</Button></View>{error ? <Message>{error}</Message> : !result ? <Loading /> : result.content.length ? <><View style={styles.grid}>{result.content.map((product) => <ProductCard key={product.id} product={product} />)}</View><Pagination page={page} totalPages={result.totalPages} first={result.first} last={result.last} onPage={setPage} /></> : <Empty title="Nenhum produto encontrado" text="Tente ajustar seus filtros para descobrir mais peças." />}</Screen>; }
const styles = StyleSheet.create({ filters: { gap: 13, borderWidth: 1, padding: 15, borderRadius: 9 }, row: { flexDirection: 'row', gap: 10 }, grid: { gap: 14 } });
