import { useEffect, useState } from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { Link, useRouter } from 'expo-router';
import { Button, Loading, Message, Screen } from '@/src/components/ui';
import { ProductCard } from '@/src/components/ProductCard';
import { api } from '@/src/lib/api';
import { Product } from '@/src/types/models';
import { useApp } from '@/src/context/AppContext';
export default function Home() { const router = useRouter(); const { colors } = useApp(); const [products, setProducts] = useState<Product[]>([]); const [error, setError] = useState(''); useEffect(() => { api.products('?page=0').then((data) => setProducts(data.content.slice(-3))).catch((e) => setError(e.message)); }, []); return <Screen><View style={[styles.hero, { backgroundColor: colors.cream }]}><Text style={[styles.eyebrow, { color: colors.green }]}>COMPRA E VENDA DE ELETRÔNICOS</Text><Text style={[styles.heroTitle, { color: colors.ink }]}>Peças que movem <Text style={{ color: colors.green, fontStyle: 'italic' }}>ideias.</Text></Text><Text style={[styles.copy, { color: colors.copy }]}>Encontre componentes eletrônicos, dê novo destino ao que já não usa e transforme projetos em realidade.</Text><View style={styles.actions}><View style={{ flex: 1 }}><Button onPress={() => router.push('/(tabs)/feed')}>Explorar produtos</Button></View><View style={{ flex: 1 }}><Button variant="secondary" onPress={() => router.push('/(tabs)/anunciar')}>Anunciar peça</Button></View></View></View><View style={styles.sectionHead}><View><Text style={[styles.eyebrow, { color: colors.green }]}>RECÉM-CHEGADOS</Text><Text style={[styles.title, { color: colors.ink }]}>Novidades no mercado</Text></View><Link href="/(tabs)/feed" style={{ color: colors.green, fontFamily: 'Manrope_800ExtraBold', fontSize: 12 }}>Ver todos →</Link></View>{error ? <Message>{error}</Message> : products.length ? <View style={styles.grid}>{products.map((product) => <ProductCard key={product.id} product={product} />)}</View> : <Loading />}</Screen>; }
const styles = StyleSheet.create({ hero: { marginHorizontal: -20, padding: 27, gap: 16 }, eyebrow: { fontFamily: 'DMMono_500Medium', fontSize: 10, letterSpacing: 1.1 }, heroTitle: { fontFamily: 'PlayfairDisplay_700Bold', fontSize: 49, lineHeight: 52, letterSpacing: -1.5 }, copy: { fontFamily: 'Manrope_400Regular', fontSize: 15, lineHeight: 23 }, actions: { flexDirection: 'row', gap: 10, marginTop: 5 }, sectionHead: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-end', marginTop: 18 }, title: { fontFamily: 'PlayfairDisplay_700Bold', fontSize: 29 }, grid: { gap: 14 } });
