import { useEffect, useState } from 'react';
import { Image, StyleSheet, Text, View } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { Button, Loading, Message, Screen } from '@/src/components/ui';
import { api } from '@/src/lib/api';
import { imageSource, money } from '@/src/lib/format';
import { Product } from '@/src/types/models';
import { useApp } from '@/src/context/AppContext';
export default function ProductDetail() { const { id } = useLocalSearchParams<{ id: string }>(); const router = useRouter(); const { colors, addToCart, showNotice } = useApp(); const [product, setProduct] = useState<Product | null>(null); const [rating, setRating] = useState<number | null>(null); const [error, setError] = useState(''); useEffect(() => { api.product(id).then(setProduct).catch((e) => setError(e.message)); }, [id]); useEffect(() => { if (product?.id_vendedor) api.sellerRating(product.id_vendedor).then(setRating).catch(() => undefined); }, [product]); const add = async () => { if (!product) return; const wasAdded = await addToCart(product); showNotice(wasAdded ? 'Produto adicionado ao carrinho.' : 'Este produto já está no carrinho.', wasAdded ? 'success' : 'error'); }; if (error) return <Screen title="Não foi possível abrir o produto" back><Message>{error}</Message></Screen>; if (!product) return <Screen back><Loading /></Screen>; const image = imageSource(product); return <Screen back><View style={[styles.detail, { backgroundColor: colors.surface, borderColor: colors.line }]}><View style={[styles.imageBox, { backgroundColor: colors.surfaceMuted }]}>{image ? <Image source={{ uri: image }} style={styles.image} /> : <Text style={{ color: colors.muted }}>Sem imagem</Text>}</View><View style={styles.content}><Text style={[styles.category, { color: colors.green }]}>{product.categoria || 'ELETRÔNICOS'} · {product.condicao || 'DISPONÍVEL'}</Text><Text style={[styles.title, { color: colors.ink }]}>{product.nome}</Text><Text style={[styles.price, { color: colors.greenDark }]}>{money(product.preco)}</Text><Text style={[styles.copy, { color: colors.copy }]}>{product.detalhes || 'Este vendedor ainda não adicionou detalhes a este anúncio.'}</Text><View style={[styles.seller, { borderLeftColor: colors.lime }]}><Text style={{ color: colors.muted }}>Vendido por</Text><Text style={{ color: colors.ink, fontFamily: 'Manrope_800ExtraBold' }}>{product.nome_do_usuario || product.nomeUsuario || 'Vendedor O.M.C.E'}</Text>{rating !== null && <Text style={{ color: colors.muted }}>★ {Number(rating).toFixed(1)} de avaliação</Text>}</View><Button onPress={add}>Adicionar ao carrinho</Button><Button variant="secondary" onPress={() => router.push(`/produto/${id}/avaliacoes`)}>Ver avaliações</Button></View></View></Screen>; }
const styles = StyleSheet.create({ detail: { borderWidth: 1, borderRadius: 9, overflow: 'hidden' }, imageBox: { height: 310, alignItems: 'center', justifyContent: 'center' }, image: { width: '100%', height: '100%', resizeMode: 'cover' }, content: { padding: 20, gap: 14 }, category: { fontFamily: 'DMMono_500Medium', fontSize: 10, letterSpacing: .8 }, title: { fontFamily: 'PlayfairDisplay_700Bold', fontSize: 36, lineHeight: 42 }, price: { fontFamily: 'Manrope_800ExtraBold', fontSize: 25 }, copy: { fontFamily: 'Manrope_400Regular', lineHeight: 23, fontSize: 15 }, seller: { borderLeftWidth: 3, paddingLeft: 12, gap: 4, marginVertical: 4 } });
