import { useEffect, useState } from 'react';
import { Image, StyleSheet, Text, View } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { Button, Empty, Loading, Message, Pagination, Screen } from '@/src/components/ui';
import { api } from '@/src/lib/api';
import { imageSource, money } from '@/src/lib/format';
import { PageResult, Product } from '@/src/types/models';
import { useApp } from '@/src/context/AppContext';
export default function History() { const { type } = useLocalSearchParams<{ type: 'compras' | 'vendas' }>(); const purchases = type === 'compras'; const router = useRouter(); const { session, colors } = useApp(); const [page, setPage] = useState(0); const [result, setResult] = useState<PageResult<Product> | null>(null); const [error, setError] = useState(''); useEffect(() => { if (session) { setResult(null); api.history(purchases ? 'compra' : 'vendas', page, session.id).then(setResult).catch((e) => setError(e.message)); } }, [page, purchases, session]); return <Screen eyebrow="HISTÓRICO" title={purchases ? 'Minhas compras' : 'Minhas vendas'} back>{error ? <Message>{error}</Message> : !result ? <Loading /> : result.content.length ? <><View style={styles.list}>{result.content.map((product) => { const image = imageSource(product); return <View key={product.id} style={[styles.item, { backgroundColor: colors.surface, borderColor: colors.line }]}>{image && <Image source={{ uri: image }} style={styles.image} />}<View style={styles.info}><Text style={[styles.category, { color: colors.green }]}>{product.categoria || 'PRODUTO'}</Text><Text style={[styles.name, { color: colors.ink }]}>{product.nome}</Text><Text style={[styles.price, { color: colors.green }]}>{money(product.preco)}</Text><View style={styles.actions}><Button variant="secondary" onPress={() => router.push(`/produto/${product.id}`)}>Ver produto</Button>{purchases && <Button variant="secondary" onPress={() => router.push(`/produto/${product.id}/avaliar`)}>Avaliar produto</Button>}{purchases && product.id_vendedor && <Button variant="secondary" onPress={() => router.push(`/vendedor/${product.id_vendedor}/avaliar`)}>Avaliar vendedor</Button>}</View></View></View>; })}</View><Pagination page={page} totalPages={result.totalPages} first={result.first} last={result.last} onPage={setPage} /></> : <Empty title="Ainda não há movimentações" text={purchases ? 'As suas compras aparecerão aqui.' : 'As vendas dos seus produtos aparecerão aqui.'} />}</Screen>; }
const styles = StyleSheet.create({ list: { gap: 13 }, item: { borderWidth: 1, borderRadius: 8, padding: 13, flexDirection: 'row', gap: 13 }, image: { width: 78, height: 75, borderRadius: 5, resizeMode: 'cover' }, info: { flex: 1, gap: 4 }, category: { fontFamily: 'DMMono_500Medium', fontSize: 9, letterSpacing: .8 }, name: { fontFamily: 'Manrope_800ExtraBold', fontSize: 15 }, price: { fontFamily: 'Manrope_800ExtraBold', fontSize: 14 }, actions: { marginTop: 7, flexDirection: 'row', flexWrap: 'wrap', gap: 7 } });
