import { useEffect, useState } from 'react';
import { Image, Pressable, StyleSheet, Text, View } from 'react-native';
import * as ImagePicker from 'expo-image-picker';
import { useRouter } from 'expo-router';
import { Button, Choice, Field, Loading, Message, Screen } from '@/src/components/ui';
import { categoryOptions } from '@/src/constants/theme';
import { api } from '@/src/lib/api';
import { Product } from '@/src/types/models';
import { imageSource } from '@/src/lib/format';
import { useApp } from '@/src/context/AppContext';

export function ProductForm({ id }: { id?: string }) {
  const edit = Boolean(id); const router = useRouter(); const { session, colors, showNotice } = useApp(); const [current, setCurrent] = useState<Product | null>(null); const [name, setName] = useState(''); const [price, setPrice] = useState(''); const [details, setDetails] = useState(''); const [condition, setCondition] = useState(''); const [category, setCategory] = useState(''); const [image, setImage] = useState<{ base64: string; type: string; uri: string } | null>(null); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  useEffect(() => { if (!id) return; api.product(id).then((product) => { setCurrent(product); setName(product.nome); setPrice(String(product.preco)); setDetails(product.detalhes || ''); setCondition(product.condicao || ''); setCategory(product.categoria || ''); }).catch((e) => setError(e.message)); }, [id]);
  const chooseImage = async () => { const permission = await ImagePicker.requestMediaLibraryPermissionsAsync(); if (!permission.granted) return setError('Permita o acesso às fotos para escolher uma imagem.'); const result = await ImagePicker.launchImageLibraryAsync({ mediaTypes: ['images'], allowsEditing: true, quality: .75, base64: true }); const asset = result.assets?.[0]; if (!result.canceled && asset?.base64) setImage({ base64: asset.base64, type: asset.mimeType || 'image/jpeg', uri: asset.uri }); };
  const submit = async () => { if (!session) return; if (!name || !price || !details || !condition || !category) return setError('Preencha todos os dados do anúncio.'); if (!edit && !image) return setError('Escolha uma imagem para anunciar o produto.'); setSaving(true); setError(''); try { if (edit) await api.updateProduct({ id: Number(id), nome: name, preco: Number(price), detalhes: details, imagem: image?.base64 || current?.imagem || current?.Imagem, imagem_tipo: image?.type || current?.imagem_tipo || current?.Imagem_tipo }); else await api.createProduct({ nome: name, preco: Number(price), detalhes: details, condicao: condition, categoria: category, id_usuario: Number(session.id), imagem: image!.base64, imagem_tipo: image!.type }); showNotice(edit ? 'Produto atualizado com sucesso.' : 'Produto anunciado com sucesso.'); router.replace(edit ? `/produto/${id}` : '/(tabs)/feed'); } catch (e) { setError(e instanceof Error ? e.message : 'Não foi possível salvar o anúncio.'); } finally { setSaving(false); } };
  if (edit && !current && !error) return <Screen title="Editar produto" back><Loading /></Screen>;
  const currentImage = image?.uri || imageSource(current);
  return <Screen eyebrow={edit ? 'GERENCIAR ANÚNCIO' : 'NOVO ANÚNCIO'} title={edit ? 'Edite seu produto' : 'Anuncie uma peça'} back>{error && <Message>{error}</Message>}<View style={[styles.card, { borderColor: colors.line, backgroundColor: colors.surface }]}><Field label="Nome do produto" value={name} onChangeText={setName} placeholder="Ex.: Kit ESP32 DevKit" /><Field label="Preço" value={price} onChangeText={setPrice} keyboardType="decimal-pad" placeholder="0,00" /><Choice label="Condição" value={condition} options={['NOVO', 'USADO']} onChange={setCondition} /><Choice label="Categoria" value={category} options={categoryOptions} onChange={setCategory} /><Field label="Detalhes" value={details} onChangeText={setDetails} multiline numberOfLines={5} textAlignVertical="top" style={{ minHeight: 125, paddingTop: 12 }} placeholder="Descreva o estado, especificações e o que acompanha o produto." /><View style={{ gap: 8 }}><Text style={[styles.label, { color: colors.ink }]}>Imagem</Text><Pressable onPress={chooseImage} style={[styles.imagePick, { borderColor: colors.input, backgroundColor: colors.surfaceMuted }]}>{currentImage ? <Image source={{ uri: currentImage }} style={styles.preview} /> : <Text style={{ color: colors.muted }}>Selecionar imagem da galeria</Text>}</Pressable><Button variant="secondary" onPress={chooseImage}>{currentImage ? 'Trocar imagem' : 'Escolher imagem'}</Button></View><Button onPress={submit} disabled={saving}>{saving ? 'Salvando…' : edit ? 'Salvar alterações' : 'Publicar anúncio'}</Button></View></Screen>;
}
const styles = StyleSheet.create({ card: { padding: 18, gap: 17, borderRadius: 9, borderWidth: 1 }, label: { fontFamily: 'Manrope_700Bold', fontSize: 13 }, imagePick: { height: 180, overflow: 'hidden', borderRadius: 7, borderWidth: 1, justifyContent: 'center', alignItems: 'center' }, preview: { width: '100%', height: '100%', resizeMode: 'cover' } });
