version: '3.8'
services:
  mysql_db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: senha_root
      MYSQL_DATABASE: omce
      MYSQL_USER: usuario
      MYSQL_PASSWORD: senha
    command: --max_allowed_packet=16M
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql  # Docker gerencia o volume automaticamente
volumes:
  mysql_data: