import { useEffect, useState } from 'react';
import { auth, request } from '../../api';
import { useNotice } from '../../contexts/NoticeContext';
import { ErrorMessage, Loading } from '../../components/ui/Feedback';
import Page from '../../components/ui/Page';

export default function Profile() {
  const notice = useNotice(); const [user, setUser] = useState(null); const [address, setAddress] = useState({}); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  useEffect(() => { request(`/user/${auth.userId}`).then((data) => { setUser(data); setAddress(data.endereco || {}); }).catch((requestError) => setError(requestError.message)); }, []);
  const submit = async (event) => { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget)); setSaving(true); try { await request('/user/alterardados', { method: 'PUT', body: JSON.stringify({ ...user, ...values, id: Number(auth.userId), endereco: { ...address, pais: 'Brasil' }, novaSenha: values.novaSenha }) }); localStorage.setItem('nome', values.nome); notice({ message: 'Dados atualizados com sucesso.' }); } catch (requestError) { setError(requestError.message); } finally { setSaving(false); } };
  if (!user && !error) return <Loading />;
  return <Page eyebrow="MINHA CONTA" title="Seus dados">{error ? <ErrorMessage error={error} /> : <form className="form-card profile-form" onSubmit={submit}><div className="form-row"><label>Nome<input name="nome" defaultValue={user.nome} required /></label><label>Nome de usuário<input name="nomeUser" defaultValue={user.nomeUser} required /></label></div><div className="form-row"><label>E-mail<input name="email" type="email" defaultValue={user.email} required /></label><label>Telefone<input name="telefone" defaultValue={user.telefone} required /></label></div><div className="form-row"><label>CPF<input name="cpf" defaultValue={user.cpf} required /></label><label>Data de nascimento<input name="dataNasc" type="date" defaultValue={user.dataNasc} required /></label></div><h2>Endereço</h2><label>CEP<input value={address.cep || ''} onChange={(event) => setAddress({ ...address, cep: event.target.value })} /></label><div className="form-row"><label>Logradouro<input value={address.logradouro || ''} onChange={(event) => setAddress({ ...address, logradouro: event.target.value })} /></label><label>Cidade<input value={address.cidade || ''} onChange={(event) => setAddress({ ...address, cidade: event.target.value })} /></label><label>Estado<input value={address.estado || ''} onChange={(event) => setAddress({ ...address, estado: event.target.value })} /></label></div><h2>Segurança</h2><div className="form-row"><label>Senha atual<input type="password" name="senha" required /></label><label>Nova senha <small>(opcional)</small><input type="password" name="novaSenha" /></label></div><button className="button primary" disabled={saving}>{saving ? 'Salvando…' : 'Salvar alterações'}</button></form>}</Page>;
}
